import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "~/components/navigation/navbar";
import { SideNav } from "~/components/navigation/side-nav";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar locale={locale} />
        <main className="flex gap-5">
          <div className="hidden md:flex">
            <SideNav locale={locale} />
          </div>
          <div className="p-10 w-full">{children}</div>
        </main>
      </body>
    </html>
  );
}
